---

- hosts: "{{ server_fqdn }}"
  remote_user: root
  roles:
    - stancel.setup-mysql-backups
    - stancel.install-bareos-client 

- hosts: "{{ bareos_server_fqdn }}"
  become: true
  become_method: sudo
  roles:
    - stancel.add-job-to-bareos-director





