# Role Requirements are placed here. Some examples are below:

# Install a role from Ansible Galaxy
# - src: zaiste.nginx

# Install a role from Github
# - name: essentials
#   src: https://github.com/zaiste/ansible-essentials

# Install a role from Github using a branch
#- name: essentials
#  src: https://github.com/zaiste/ansible-essentials
#  version: origin/master

# Install a role from Github using a tag
#- name: essentials
#  src: https://github.com/zaiste/ansible-essentials
#  version: 0.0.3


#- name: add-job-to-bareos-director
#  src: https://github.com/stancel/add-job-to-bareos-director
#  version: 1.0.0

#- name: setup-mysql-backups
#  src: https://github.com/stancel/setup-mysql-backups
#  version: 1.0.0

#- name: install-bareos-client
#  src: https://github.com/stancel/install-bareos-client
#  version: 1.0.0

- src: stancel.add-job-to-bareos-director

- src: stancel.setup-mysql-backups

- src: stancel.install-bareos-client



